[package]
name = "chemp"
version = "0.9.0"
edition = "2021"
description = "chemical formulas parser"
license = ""
homepage = "https://github.com/smrnwow/chemp"
repository = "https://github.com/smrnwow/chemp"
documentation = ""

[dependencies]
once_cell = "1.19.0"
